# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
url: 'https://mydomain.com'
baseurl: ''
title: 'EndoCV'
description: 'Building fundamental computer vision methods in Endoscopy'
permalink: pretty
logo: "https://drive.google.com/uc?id=1CiYIAx5hmn0ZgVRydlRX_0afBohIZUQp"
email: "sharib.ali@eng.ox.ac.uk"
css_inline: true

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Publications
  url: /publications/
- title: Gallery
  url: /gallary/
- title: Events
  url: /events/
- title: People
  url: /people/
- title: Support
  url: /support/
- title: News
  url: /news/
- title: Categories
  url: /categories/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "International events in endoscopy"
    feature_text: |
      Events
    feature_image: "https://picsum.photos/2560/600?image=866"
